#include "bridge.hpp"
#include "terminal_qr.hpp"
#include <rang.hpp>

/******************************************************************************
Finite State Machine
Project: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
Description: ProjectName

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 0.0.0
Generation date: 2026-04-03 10:47:21
Generated from: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
The finite state machine has:
  4 states
  1 transition functions

******************************************************************************/
    
using namespace std;
using namespace rang;

namespace {

std::string startup_process_label(std::string agent_name) {
  if (!agent_name.empty()) {
    agent_name.front() = static_cast<char>(std::toupper(agent_name.front()));
  }
  return agent_name + " process started";
}

void print_websocket_addresses(const MadsWebsockets::BridgeRuntime &runtime) {
  auto addresses = runtime.websocket_external_addresses();
  std::cout << "  Websocket addr:   " << style::bold;
  if (addresses.empty()) {
    std::cout << "<no external address found>";
  } else {
    for (std::size_t index = 0; index < addresses.size(); ++index) {
      if (index != 0) {
        std::cout << "\n                    ";
      }
      std::cout << addresses[index];
    }
  }
  std::cout << style::reset << std::endl;
}

void print_websocket_qr(const MadsWebsockets::BridgeRuntime &runtime) {
  auto payload = runtime.websocket_bootstrap_payload();
  if (!payload.has_value()) {
    return;
  }

  auto qr = MadsWebsockets::render_terminal_qr(*payload);
  if (qr.empty()) {
    return;
  }

  std::cout << "  Bootstrap QR:" << std::endl;
  std::cout << qr;
}

void print_connected_clients_line(std::size_t count, bool overwrite = false) {
  if (overwrite) {
    std::cout << "\r\033[2K";
  }
  std::cout << "Connected clients: " << style::bold << count << style::reset;
  if (!overwrite) {
    std::cout << std::endl;
  } else {
    std::cout << std::flush;
  }
}

}
    
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace FSM {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE
template<class T> 
state_t do_init(T &data) {
  if (!data.runtime.initialize()) {
    return FSM::STATE_STOP;
  }
  data.runtime.agent().info(cout);
  print_websocket_addresses(data.runtime);
  print_websocket_qr(data.runtime);
  std::cout << startup_process_label(data.runtime.agent_name()) << std::endl;
  print_connected_clients_line(data.runtime.connected_clients(), true);
  return FSM::STATE_IDLE;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_RUN, STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  switch (data.runtime.idle()) {
  case MadsWebsockets::RuntimeDecision::run:
    return FSM::STATE_RUN;
  case MadsWebsockets::RuntimeDecision::stop:
    return FSM::STATE_STOP;
  case MadsWebsockets::RuntimeDecision::idle:
  case MadsWebsockets::RuntimeDecision::stay:
  default:
    return FSM::STATE_IDLE;
  }
}

// Function to be executed in state STATE_RUN
// valid return states: NO_CHANGE, STATE_RUN, STATE_IDLE
template<class T> 
state_t do_run(T &data) {
  auto next = data.runtime.run_once();
  std::size_t client_count = 0;
  auto changed = data.runtime.consume_client_count_changed(client_count);
  switch (next) {
  case MadsWebsockets::RuntimeDecision::idle:
    if (changed) {
      print_connected_clients_line(client_count, true);
    }
    return FSM::STATE_IDLE;
  case MadsWebsockets::RuntimeDecision::stop:
    if (changed) {
      print_connected_clients_line(client_count, true);
    }
    return FSM::STATE_STOP;
  case MadsWebsockets::RuntimeDecision::run:
  case MadsWebsockets::RuntimeDecision::stay:
  default:
    if (changed) {
      print_connected_clients_line(client_count, true);
    }
    return FSM::STATE_RUN;
  }
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  std::cout << std::endl;
  data.runtime.shutdown();
  return FSM::NO_CHANGE;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from run to idle
template<class T>
void reset(T &data) {
  data.runtime.reset();
}


}; // namespace FSM
