/******************************************************************************
Finite State Machine
Project: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
Description: ProjectName

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 0.0.0
Generation date: 2026-04-03 10:47:21
Generated from: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
The finite state machine has:
  4 states
  1 transition functions

******************************************************************************/
#ifndef FSM_AGENT_HPP
#define FSM_AGENT_HPP
#include <functional>
#include <iostream>
#include <map>
#include <string>
#include <tuple>


using namespace std::string_literals;
namespace FSM {

// List of states
typedef enum {
  STATE_INIT,
  STATE_IDLE,
  STATE_RUN,
  STATE_STOP,
  NUM_STATES,
  NO_CHANGE,
  UNIMPLEMENTED
} state_t;

// State human-readable names
std::map<state_t, char const *> state_names = {
  { STATE_INIT, "INIT" },
  { STATE_IDLE, "IDLE" },
  { STATE_RUN, "RUN" },
  { STATE_STOP, "STOP" },
  { NUM_STATES, "NUM_STATES" },
  { NO_CHANGE, "NO_CHANGE" },
  { UNIMPLEMENTED, "UNIMPLEMENTED" }
};

// Custom state functions:
template<class T> 
state_t do_init(T &data);
template<class T> 
state_t do_idle(T &data);
template<class T> 
state_t do_run(T &data);
template<class T> 
state_t do_stop(T &data);

// Custom transition functions:
template<class T>
void reset(T &data);

// Finite State Machine class
template <typename DATA_T> 
class FiniteStateMachine {

// Function templates
using state_fun = std::function<state_t(DATA_T &data)>;
using transition_fun = std::function<void(DATA_T &data)>;
using operation_fun = std::function<void(DATA_T &data)>;

private:
  std::pair<state_t, state_t> _state{ STATE_INIT, STATE_INIT };
  std::map<state_t, state_fun> _states;
  std::map<state_t, std::map<state_t, transition_fun>> _transitions;
  std::function<void()> _timing_func;
  DATA_T *_data;

public:

  FiniteStateMachine(DATA_T *data) : _data(data) {
    install_functions();
  }
  ~FiniteStateMachine(){};

  void set_timing_function(std::function<void()> timing_func) {
    _timing_func = timing_func;
  }

  void add_state(state_t name, state_fun func) { _states[name] = func; }

  void add_transition(state_t from, state_t to, transition_fun func) {
    _transitions[from][to] = func;
  }

  inline state_t state() { return _state.second; }
  inline std::string state_name() { return std::string(state_names[_state.second]); }
  inline state_t prev_state() { return _state.first; }

  state_t operator()(state_t state) {
    if (_states.find(state) == _states.end()) {
      throw std::runtime_error("State not found: "s + state_names[state]);
    }
    state_t next = _states[state](*_data);
    if (next == NO_CHANGE) {
      next = state;
    }
    return next;
  }

  void operator()(state_t from, state_t to) {
    if (_transitions.find(from) != _transitions.end()) {
      if (_transitions[from].find(to) != _transitions[from].end()) {
        _transitions[from][to](*_data);
      }
    }
  }


  // Setup initial state links
  void setup(state_t state) {
    _state.first = state;
    _state.second = state;
  }

  // Evaluate the current state and update the next state
  // to be used when main loop is customized (i.e., not using FSM::run())
  state_t eval_state() {
      _state.first = _state.second;
      _state.second = (*this)(_state.second);
      (*this)(_state.first, _state.second);
      return _state.second;
  }

  // Run the FSM from a given state
  void run(state_t state, operation_fun operation = nullptr) {
    setup(state);
    do {
      if (operation) {
        operation(*_data);
      }
      eval_state();
      if (_timing_func) {
        _timing_func();
      }
    } while (_state.second != STATE_STOP);
    // Call the exit state once more:
    (*this)(STATE_STOP);
  }

  // Run the FSM from the initial state
  void run(operation_fun operation = nullptr) { run(STATE_INIT, operation); }

  // install state and transition functions
  void install_functions() {

    // State functions
    add_state(FSM::STATE_INIT, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_init(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "INIT");
        break;
      case FSM::STATE_IDLE:
        break;
      default:
        next_state = FSM::NO_CHANGE;
      }
      return next_state;
    });

    add_state(FSM::STATE_IDLE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_idle(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "IDLE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_IDLE:
      case FSM::STATE_RUN:
      case FSM::STATE_STOP:
        break;
      default:
        next_state = FSM::NO_CHANGE;
      }
      return next_state;
    });

    add_state(FSM::STATE_RUN, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_run(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "RUN");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_RUN:
      case FSM::STATE_IDLE:
        break;
      default:
        next_state = FSM::NO_CHANGE;
      }
      return next_state;
    });

    add_state(FSM::STATE_STOP, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_stop(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "STOP");
        break;
      case FSM::NO_CHANGE:
        break;
      default:
        next_state = FSM::NO_CHANGE;
      }
      return next_state;
    });


    // Transition functions
    add_transition(STATE_RUN, STATE_IDLE, [](DATA_T &data) {
      reset(data);
    });

  }

}; // class FiniteStateMachine

}; // namespace FSM

#include "fsm_agent_impl.hpp"

#endif // FSM_AGENT_HPP
