#include "bridge.hpp"

/******************************************************************************
Finite State Machine
Project: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
Description: ProjectName

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 0.0.0
Generation date: 2026-04-03 10:47:21
Generated from: /Users/p4010/Develop/MADS_plugins/websockets_agent/fsm.dot
The finite state machine has:
  4 states
  1 transition functions

******************************************************************************/
    
using namespace std;
    
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace FSM {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE
template<class T> 
state_t do_init(T &data) {
  if (!data.runtime.initialize()) {
    return FSM::STATE_STOP;
  }
  return FSM::STATE_IDLE;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_RUN, STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  switch (data.runtime.idle()) {
  case MadsWebsockets::RuntimeDecision::run:
    return FSM::STATE_RUN;
  case MadsWebsockets::RuntimeDecision::stop:
    return FSM::STATE_STOP;
  case MadsWebsockets::RuntimeDecision::idle:
  case MadsWebsockets::RuntimeDecision::stay:
  default:
    return FSM::STATE_IDLE;
  }
}

// Function to be executed in state STATE_RUN
// valid return states: NO_CHANGE, STATE_RUN, STATE_IDLE
template<class T> 
state_t do_run(T &data) {
  switch (data.runtime.run_once()) {
  case MadsWebsockets::RuntimeDecision::idle:
    return FSM::STATE_IDLE;
  case MadsWebsockets::RuntimeDecision::stop:
    return FSM::STATE_STOP;
  case MadsWebsockets::RuntimeDecision::run:
  case MadsWebsockets::RuntimeDecision::stay:
  default:
    return FSM::STATE_RUN;
  }
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  data.runtime.shutdown();
  return FSM::NO_CHANGE;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from run to idle
template<class T>
void reset(T &data) {
  data.runtime.reset();
}


}; // namespace FSM

